<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Service\RegionSeedData;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Baseline (#367): replaces the full prior migration history (105 files, `Version20260428042314`
 * through `Version20260803090000`) with the schema and seed data those migrations produced,
 * verified by replaying the old chain into a scratch database and diffing the result against this
 * migration's own output before the old files were deleted.
 *
 * There is no production instance and no real data anywhere in this project (confirmed by
 * Version20260803090000's own docblock and reiterated directly) -- this is exactly the moment to
 * do this, before a real launch makes reconciling live data part of the exercise. Doing it now
 * means every environment (dev, CI, a fresh clone) starts from one migration instead of replaying
 * 105, most of which either seed tables that get wiped-without-restore later in the old chain
 * (`payment_method`/`payment_term`/`credit_memo_type`/`sales_tax`/`shipping_zone` -- admin
 * re-populates these from the UI, so they stay empty here too) or repair/backfill rows that never
 * existed because there was never real data to corrupt.
 *
 * The schema below was generated by `doctrine:migrations:diff` against current entity mappings,
 * then hand-augmented with:
 *   - four tables `diff` cannot see because nothing maps them to an entity (`payment_term`,
 *     `credit_memo_type`, `shipping_zone` -- raw DBAL only, see RawSqlTablesSurviveTheChainTest --
 *     and `db_console_throttle`, the rate-limit store for the db-admin.php gateway that runs
 *     outside the kernel);
 *   - the 22 `email_template` rows and 22 `app_setting` rows the old chain's seed/repair/content
 *     migrations left behind, copied verbatim from a full replay of that chain rather than
 *     re-derived by re-reading years of incremental fixes;
 *   - `geo_country`/`geo_province`, built from `RegionSeedData` (already the single source of
 *     truth `RegionSeeder` and the address-normalisation logic use) rather than as literal SQL.
 *
 * tests/Migrations/RawSqlTablesSurviveTheChainTest.php and
 * tests/Migrations/EmailTemplateHardcodesFixedTest.php replay this migration the same way they
 * replayed the old chain and assert on the same end state -- both passed unchanged against this
 * file before the 104 old ones were removed.
 */
final class Version20260803150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline: replaces the full prior migration history with current schema + seed data (#367).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_column_preference (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, view_key VARCHAR(64) NOT NULL, columns CLOB NOT NULL, updated_at DATETIME NOT NULL, admin_id INTEGER DEFAULT NULL, CONSTRAINT FK_52A625FC642B8210 FOREIGN KEY (admin_id) REFERENCES admin_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_52A625FC642B8210 ON admin_column_preference (admin_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_column_preference ON admin_column_preference (admin_id, view_key)');
        $this->addSql('CREATE TABLE admin_user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles CLOB NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, phone_number VARCHAR(40) DEFAULT NULL, status VARCHAR(32) NOT NULL, reset_token VARCHAR(255) DEFAULT NULL, reset_token_expires_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_admin_user_email ON admin_user (email)');
        $this->addSql('CREATE TABLE api_credential (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, company_id INTEGER NOT NULL, api_key VARCHAR(100) NOT NULL, status VARCHAR(32) NOT NULL, technical_contact_email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_credential_company_id ON api_credential (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_credential_api_key ON api_credential (api_key)');
        $this->addSql('CREATE TABLE api_credential_category (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, category_id INTEGER NOT NULL, created_at DATETIME NOT NULL, credential_id INTEGER NOT NULL, CONSTRAINT FK_766AA4312558A7A5 FOREIGN KEY (credential_id) REFERENCES api_credential (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_766AA4312558A7A5 ON api_credential_category (credential_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_credential_category ON api_credential_category (credential_id, category_id)');
        $this->addSql('CREATE TABLE app_setting (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, setting_key VARCHAR(120) NOT NULL, name VARCHAR(180) NOT NULL, setting_value CLOB DEFAULT NULL, description CLOB DEFAULT NULL, category VARCHAR(60) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_app_setting_key ON app_setting (setting_key)');
        $this->addSql('CREATE TABLE audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, occurred_at DATETIME NOT NULL, actor_type VARCHAR(16) NOT NULL, actor_id INTEGER DEFAULT NULL, actor_name VARCHAR(255) NOT NULL, area VARCHAR(80) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id INTEGER DEFAULT NULL, "action" VARCHAR(64) NOT NULL, summary CLOB NOT NULL, data_before CLOB DEFAULT NULL, data_after CLOB DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL)');
        $this->addSql('CREATE TABLE bundle_status (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, source VARCHAR(100) NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A9F47C95F8A7F73 ON bundle_status (source)');
        $this->addSql('CREATE TABLE cart (po_number VARCHAR(80) DEFAULT NULL, user_name VARCHAR(120) DEFAULT NULL, po_date DATE DEFAULT NULL, subtotal NUMERIC(12, 2) NOT NULL, tax NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, source VARCHAR(32) NOT NULL, special_instructions VARCHAR(255) DEFAULT NULL, fee_lines CLOB DEFAULT NULL, coupon_codes CLOB DEFAULT NULL, tax_lines CLOB DEFAULT NULL, company_snapshot CLOB DEFAULT NULL, shipping_method VARCHAR(120) DEFAULT NULL, fulfillment_region VARCHAR(160) DEFAULT NULL, created_at DATETIME NOT NULL, id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, session_id VARCHAR(128) NOT NULL, hold_expires_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, company_id INTEGER DEFAULT NULL, CONSTRAINT FK_BA388B7979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA388B7613FECDF ON cart (session_id)');
        $this->addSql('CREATE INDEX IDX_BA388B7979B1AD6 ON cart (company_id)');
        $this->addSql('CREATE TABLE cart_address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type VARCHAR(16) NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, email_primary VARCHAR(255) DEFAULT NULL, email_secondary VARCHAR(255) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, fax VARCHAR(40) DEFAULT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, province VARCHAR(6) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, delivery_instructions CLOB DEFAULT NULL, source_address_id INTEGER DEFAULT NULL, cart_id INTEGER NOT NULL, CONSTRAINT FK_F694A7868903DE51 FOREIGN KEY (source_address_id) REFERENCES company_address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F694A7861AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_F694A7868903DE51 ON cart_address (source_address_id)');
        $this->addSql('CREATE INDEX IDX_F694A7861AD5CDBF ON cart_address (cart_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cart_address_type ON cart_address (cart_id, type)');
        $this->addSql('CREATE TABLE cart_hold (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, cart_item_id INTEGER NOT NULL, CONSTRAINT FK_F02F0D3EE9B59A59 FOREIGN KEY (cart_item_id) REFERENCES cart_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F02F0D3EE9B59A59 ON cart_hold (cart_item_id)');
        $this->addSql('CREATE TABLE cart_item (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, quantity INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, cart_id INTEGER NOT NULL, product_id INTEGER NOT NULL, fulfillment_region_id INTEGER NOT NULL, CONSTRAINT FK_F0FE25271AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F0FE25274584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F0FE252748027C30 FOREIGN KEY (fulfillment_region_id) REFERENCES fulfillment_region (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_F0FE25271AD5CDBF ON cart_item (cart_id)');
        $this->addSql('CREATE INDEX IDX_F0FE25274584665A ON cart_item (product_id)');
        $this->addSql('CREATE INDEX IDX_F0FE252748027C30 ON cart_item (fulfillment_region_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cart_item_cart_product ON cart_item (cart_id, product_id)');
        $this->addSql('CREATE TABLE company (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(80) DEFAULT NULL, status VARCHAR(32) NOT NULL, primary_email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(40) DEFAULT NULL, trade_name VARCHAR(255) DEFAULT NULL, business_license VARCHAR(80) DEFAULT NULL, sales_rep VARCHAR(120) DEFAULT NULL, account_type VARCHAR(40) NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, payment_term_id INTEGER DEFAULT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE INDEX idx_company_code ON company (code)');
        $this->addSql('CREATE TABLE company_address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, label VARCHAR(80) DEFAULT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, email_primary VARCHAR(255) DEFAULT NULL, email_secondary VARCHAR(255) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, fax VARCHAR(40) DEFAULT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, province VARCHAR(120) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, delivery_instructions CLOB DEFAULT NULL, is_default_shipping BOOLEAN DEFAULT 0 NOT NULL, is_default_billing BOOLEAN DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, company_id INTEGER NOT NULL, CONSTRAINT FK_2D1C7556979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_2D1C7556979B1AD6 ON company_address (company_id)');
        $this->addSql('CREATE TABLE company_fulfillment_region (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, company_id INTEGER NOT NULL, fulfillment_region_id INTEGER NOT NULL, price_list_id INTEGER DEFAULT NULL, CONSTRAINT FK_B3B99B1F979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B3B99B1F48027C30 FOREIGN KEY (fulfillment_region_id) REFERENCES fulfillment_region (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B3B99B1F5688DED7 FOREIGN KEY (price_list_id) REFERENCES price_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_B3B99B1F979B1AD6 ON company_fulfillment_region (company_id)');
        $this->addSql('CREATE INDEX IDX_B3B99B1F48027C30 ON company_fulfillment_region (fulfillment_region_id)');
        $this->addSql('CREATE INDEX IDX_B3B99B1F5688DED7 ON company_fulfillment_region (price_list_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_company_fulfillment_region ON company_fulfillment_region (company_id, fulfillment_region_id)');
        $this->addSql('CREATE TABLE company_note (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_name VARCHAR(255) DEFAULT NULL, text CLOB NOT NULL, created_at DATETIME NOT NULL, company_id INTEGER NOT NULL, CONSTRAINT FK_8CD0E0FA979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX idx_company_note_company ON company_note (company_id)');
        $this->addSql('CREATE TABLE company_payment_method (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, company_id INTEGER NOT NULL, payment_method_id INTEGER NOT NULL, CONSTRAINT FK_55A98E55979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_55A98E555AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_55A98E55979B1AD6 ON company_payment_method (company_id)');
        $this->addSql('CREATE INDEX IDX_55A98E555AA1164F ON company_payment_method (payment_method_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COMPANY_PAYMENT_METHOD ON company_payment_method (company_id, payment_method_id)');
        $this->addSql('CREATE TABLE custom_field_definition (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, object_type VARCHAR(20) NOT NULL, slug VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, field_type VARCHAR(20) NOT NULL, options CLOB DEFAULT NULL, visible_on_add BOOLEAN DEFAULT 1 NOT NULL, visible_on_edit BOOLEAN DEFAULT 1 NOT NULL, visible_on_listing BOOLEAN DEFAULT 0 NOT NULL, searchable BOOLEAN DEFAULT 0 NOT NULL, source VARCHAR(100) DEFAULT NULL, sort_order INTEGER DEFAULT 0 NOT NULL, category_id INTEGER DEFAULT NULL, CONSTRAINT FK_48DC853312469DE2 FOREIGN KEY (category_id) REFERENCES product_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_48DC853312469DE2 ON custom_field_definition (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CUSTOM_FIELD_DEFINITION ON custom_field_definition (object_type, slug)');
        $this->addSql('CREATE TABLE custom_field_value (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, object_id INTEGER NOT NULL, value CLOB DEFAULT NULL, definition_id INTEGER NOT NULL, CONSTRAINT FK_EC7B05D11EA911 FOREIGN KEY (definition_id) REFERENCES custom_field_definition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_EC7B05D11EA911 ON custom_field_value (definition_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CUSTOM_FIELD_VALUE ON custom_field_value (definition_id, object_id)');
        $this->addSql('CREATE TABLE custom_menu_item (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, label VARCHAR(150) NOT NULL, url VARCHAR(2048) NOT NULL, sort_order INTEGER DEFAULT 0 NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE TABLE customer_user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles CLOB NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, phone_number VARCHAR(40) DEFAULT NULL, status VARCHAR(32) NOT NULL, reset_token VARCHAR(255) DEFAULT NULL, reset_token_expires_at DATETIME DEFAULT NULL, last_login_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, company_id INTEGER DEFAULT NULL, CONSTRAINT FK_D902723E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_D902723E979B1AD6 ON customer_user (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_user_email ON customer_user (email)');
        $this->addSql('CREATE TABLE db_console_session (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at DATETIME NOT NULL, ip_address VARCHAR(45) NOT NULL, created_at DATETIME NOT NULL, admin_id INTEGER NOT NULL, CONSTRAINT FK_9BF48008642B8210 FOREIGN KEY (admin_id) REFERENCES admin_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX idx_db_console_session_admin ON db_console_session (admin_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_db_console_session_token ON db_console_session (token_hash)');
        $this->addSql('CREATE TABLE document_number_counter (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, kind VARCHAR(20) NOT NULL, prefix VARCHAR(20) NOT NULL, last_value INTEGER DEFAULT 0 NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DOC_NUMBER_COUNTER_KIND_PREFIX ON document_number_counter (kind, prefix)');
        $this->addSql('CREATE TABLE email_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, template_code VARCHAR(80) NOT NULL, recipient VARCHAR(180) NOT NULL, status VARCHAR(32) NOT NULL, body CLOB DEFAULT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE email_template (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code VARCHAR(80) NOT NULL, module VARCHAR(180) NOT NULL, sent_to VARCHAR(32) NOT NULL, subject VARCHAR(255) NOT NULL, body CLOB NOT NULL, description CLOB DEFAULT NULL, status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE TABLE error_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, level VARCHAR(32) NOT NULL, area VARCHAR(80) NOT NULL, message CLOB NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE estimate (po_number VARCHAR(80) DEFAULT NULL, user_name VARCHAR(120) DEFAULT NULL, source VARCHAR(32) NOT NULL, special_instructions VARCHAR(255) DEFAULT NULL, fee_lines CLOB DEFAULT NULL, coupon_codes CLOB DEFAULT NULL, tax_lines CLOB DEFAULT NULL, company_snapshot CLOB DEFAULT NULL, shipping_method VARCHAR(120) DEFAULT NULL, fulfillment_region VARCHAR(160) DEFAULT NULL, created_at DATETIME NOT NULL, id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, document_number VARCHAR(32) NOT NULL, status VARCHAR(20) NOT NULL, subtotal NUMERIC(12, 2) DEFAULT NULL, tax NUMERIC(12, 2) DEFAULT NULL, total NUMERIC(12, 2) DEFAULT NULL, po_date DATE NOT NULL, company_id INTEGER NOT NULL, converted_order_id INTEGER DEFAULT NULL, CONSTRAINT FK_D2EA4607979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D2EA4607AB17FB50 FOREIGN KEY (converted_order_id) REFERENCES sales_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2EA460728F2AE32 ON estimate (document_number)');
        $this->addSql('CREATE INDEX IDX_D2EA4607979B1AD6 ON estimate (company_id)');
        $this->addSql('CREATE INDEX IDX_D2EA4607AB17FB50 ON estimate (converted_order_id)');
        $this->addSql('CREATE TABLE estimate_address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type VARCHAR(16) NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, email_primary VARCHAR(255) DEFAULT NULL, email_secondary VARCHAR(255) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, fax VARCHAR(40) DEFAULT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, province VARCHAR(6) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, delivery_instructions CLOB DEFAULT NULL, source_address_id INTEGER DEFAULT NULL, estimate_id INTEGER NOT NULL, CONSTRAINT FK_10F2D37B8903DE51 FOREIGN KEY (source_address_id) REFERENCES company_address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_10F2D37B85F23082 FOREIGN KEY (estimate_id) REFERENCES estimate (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_10F2D37B8903DE51 ON estimate_address (source_address_id)');
        $this->addSql('CREATE INDEX IDX_10F2D37B85F23082 ON estimate_address (estimate_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_estimate_address_type ON estimate_address (estimate_id, type)');
        $this->addSql('CREATE TABLE estimate_line (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(120) DEFAULT NULL, sku VARCHAR(80) DEFAULT NULL, quantity NUMERIC(12, 2) NOT NULL, weight VARCHAR(80) DEFAULT NULL, unit VARCHAR(80) DEFAULT NULL, tax_code VARCHAR(80) DEFAULT NULL, cost NUMERIC(12, 2) NOT NULL, price NUMERIC(12, 2) DEFAULT NULL, subtotal NUMERIC(12, 2) DEFAULT NULL, sort_order INTEGER DEFAULT 0 NOT NULL, estimate_id INTEGER NOT NULL, product_id INTEGER DEFAULT NULL, CONSTRAINT FK_9715EDF785F23082 FOREIGN KEY (estimate_id) REFERENCES estimate (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9715EDF74584665A FOREIGN KEY (product_id) REFERENCES product_core (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_9715EDF785F23082 ON estimate_line (estimate_id)');
        $this->addSql('CREATE INDEX IDX_9715EDF74584665A ON estimate_line (product_id)');
        $this->addSql('CREATE TABLE estimate_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_name VARCHAR(255) DEFAULT NULL, comment CLOB NOT NULL, type VARCHAR(64) NOT NULL, customer_notified BOOLEAN NOT NULL, created_at DATETIME NOT NULL, estimate_id INTEGER NOT NULL, CONSTRAINT FK_E7D8106A85F23082 FOREIGN KEY (estimate_id) REFERENCES estimate (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_E7D8106A85F23082 ON estimate_log (estimate_id)');
        $this->addSql('CREATE TABLE fee (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, default_value NUMERIC(10, 4) DEFAULT 0 NOT NULL, tax_class VARCHAR(1) NOT NULL, source VARCHAR(100) NOT NULL, placement VARCHAR(20) DEFAULT \'main_line\' NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_964964B5989D9B62 ON fee (slug)');
        $this->addSql('CREATE TABLE frontend_menu_item_status (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, menu_key VARCHAR(100) NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, sort_order INTEGER DEFAULT 0 NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D70244431231659B ON frontend_menu_item_status (menu_key)');
        $this->addSql('CREATE TABLE fulfillment_region (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(160) NOT NULL, status VARCHAR(32) NOT NULL, guest_visible BOOLEAN NOT NULL, created_at DATETIME NOT NULL, guest_price_list_id INTEGER DEFAULT NULL, CONSTRAINT FK_837CA038EC92F FOREIGN KEY (guest_price_list_id) REFERENCES price_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_837CA038EC92F ON fulfillment_region (guest_price_list_id)');
        $this->addSql('CREATE TABLE geo_country (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code VARCHAR(2) NOT NULL, name VARCHAR(80) NOT NULL, status VARCHAR(32) NOT NULL, sort_order INTEGER NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_geo_country_code ON geo_country (code)');
        $this->addSql('CREATE TABLE geo_province (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code VARCHAR(6) NOT NULL, name VARCHAR(120) NOT NULL, status VARCHAR(32) NOT NULL, sort_order INTEGER NOT NULL, country_id INTEGER NOT NULL, CONSTRAINT FK_A463A3AAF92F3E70 FOREIGN KEY (country_id) REFERENCES geo_country (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_A463A3AAF92F3E70 ON geo_province (country_id)');
        $this->addSql('CREATE INDEX idx_geo_province_status ON geo_province (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_geo_province ON geo_province (country_id, code)');
        $this->addSql('CREATE TABLE inventory_bucket_change_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, bucket VARCHAR(20) NOT NULL, previous_quantity INTEGER NOT NULL, new_quantity INTEGER NOT NULL, "action" VARCHAR(60) NOT NULL, triggered_by VARCHAR(190) NOT NULL, occurred_at DATETIME NOT NULL, product_id INTEGER NOT NULL, fulfillment_region_id INTEGER NOT NULL, CONSTRAINT FK_C211BCE94584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C211BCE948027C30 FOREIGN KEY (fulfillment_region_id) REFERENCES fulfillment_region (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_C211BCE94584665A ON inventory_bucket_change_log (product_id)');
        $this->addSql('CREATE INDEX IDX_C211BCE948027C30 ON inventory_bucket_change_log (fulfillment_region_id)');
        $this->addSql('CREATE TABLE inventory_reconciliation_discrepancy (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, bucket VARCHAR(20) NOT NULL, cached_quantity INTEGER NOT NULL, recomputed_quantity INTEGER NOT NULL, source VARCHAR(60) NOT NULL, occurred_at DATETIME NOT NULL, product_id INTEGER NOT NULL, fulfillment_region_id INTEGER NOT NULL, CONSTRAINT FK_AC550DBF4584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_AC550DBF48027C30 FOREIGN KEY (fulfillment_region_id) REFERENCES fulfillment_region (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_AC550DBF4584665A ON inventory_reconciliation_discrepancy (product_id)');
        $this->addSql('CREATE INDEX IDX_AC550DBF48027C30 ON inventory_reconciliation_discrepancy (fulfillment_region_id)');
        $this->addSql('CREATE TABLE news_post (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(500) NOT NULL, excerpt CLOB DEFAULT NULL, content CLOB NOT NULL, published_at DATETIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE TABLE order_inventory_reservation (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, bucket VARCHAR(20) NOT NULL, quantity INTEGER NOT NULL, synced_quantity INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, order_id INTEGER NOT NULL, product_id INTEGER NOT NULL, fulfillment_region_id INTEGER NOT NULL, CONSTRAINT FK_33119368D9F6D38 FOREIGN KEY (order_id) REFERENCES sales_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_33119364584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_331193648027C30 FOREIGN KEY (fulfillment_region_id) REFERENCES fulfillment_region (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_33119368D9F6D38 ON order_inventory_reservation (order_id)');
        $this->addSql('CREATE INDEX IDX_33119364584665A ON order_inventory_reservation (product_id)');
        $this->addSql('CREATE INDEX IDX_331193648027C30 ON order_inventory_reservation (fulfillment_region_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_reservation_order_product_region ON order_inventory_reservation (order_id, product_id, fulfillment_region_id)');
        $this->addSql('CREATE TABLE payment_method (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, source VARCHAR(100) NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B61A1F6989D9B62 ON payment_method (slug)');
        $this->addSql('CREATE TABLE price_list (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(160) NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE product_category (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(160) NOT NULL, status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, parent_id INTEGER DEFAULT NULL, CONSTRAINT FK_CDFC7356727ACA70 FOREIGN KEY (parent_id) REFERENCES product_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_CDFC7356727ACA70 ON product_category (parent_id)');
        $this->addSql('CREATE TABLE product_core (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, sku VARCHAR(80) NOT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, is_private BOOLEAN NOT NULL, status VARCHAR(32) NOT NULL, plant VARCHAR(120) DEFAULT NULL, type VARCHAR(120) DEFAULT NULL, unit VARCHAR(80) DEFAULT NULL, weight VARCHAR(80) DEFAULT NULL, cost_price NUMERIC(12, 2) DEFAULT NULL, original_price NUMERIC(12, 2) DEFAULT NULL, default_price NUMERIC(12, 2) DEFAULT NULL, deposit NUMERIC(12, 2) DEFAULT NULL, suggested_price_type VARCHAR(20) DEFAULT NULL, suggested_price_value NUMERIC(12, 2) DEFAULT NULL, visible BOOLEAN NOT NULL, featured BOOLEAN NOT NULL, deleted BOOLEAN NOT NULL, sales_tax_code VARCHAR(40) DEFAULT NULL, shipping_class VARCHAR(80) DEFAULT NULL, sync_source VARCHAR(120) DEFAULT NULL, remarks CLOB DEFAULT NULL, short_description CLOB DEFAULT NULL, long_description CLOB DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, category_id INTEGER DEFAULT NULL, CONSTRAINT FK_E665A7EE12469DE2 FOREIGN KEY (category_id) REFERENCES product_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_E665A7EE12469DE2 ON product_core (category_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_core_sku ON product_core (sku)');
        $this->addSql('CREATE TABLE company_product_access (product_id INTEGER NOT NULL, company_id INTEGER NOT NULL, PRIMARY KEY (product_id, company_id), CONSTRAINT FK_4ADD45534584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4ADD4553979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_4ADD45534584665A ON company_product_access (product_id)');
        $this->addSql('CREATE INDEX IDX_4ADD4553979B1AD6 ON company_product_access (company_id)');
        $this->addSql('CREATE TABLE product_fee (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, value NUMERIC(10, 4) DEFAULT 0 NOT NULL, product_id INTEGER NOT NULL, fee_id INTEGER NOT NULL, CONSTRAINT FK_766630AA4584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_766630AAAB45AECA FOREIGN KEY (fee_id) REFERENCES fee (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_766630AA4584665A ON product_fee (product_id)');
        $this->addSql('CREATE INDEX IDX_766630AAAB45AECA ON product_fee (fee_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PRODUCT_FEE ON product_fee (product_id, fee_id)');
        $this->addSql('CREATE TABLE product_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, filename VARCHAR(255) NOT NULL, primary_image BOOLEAN NOT NULL, sort_order INTEGER NOT NULL, created_at DATETIME NOT NULL, product_id INTEGER NOT NULL, CONSTRAINT FK_64617F034584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX idx_product_image_product ON product_image (product_id)');
        $this->addSql('CREATE TABLE product_inventory (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, quantity INTEGER NOT NULL, reserved_quantity INTEGER NOT NULL, cart_hold_quantity INTEGER NOT NULL, pending_quantity INTEGER NOT NULL, approved_quantity INTEGER NOT NULL, updated_at DATETIME NOT NULL, product_id INTEGER NOT NULL, fulfillment_region_id INTEGER DEFAULT NULL, CONSTRAINT FK_DF8DFCBB4584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_DF8DFCBB48027C30 FOREIGN KEY (fulfillment_region_id) REFERENCES fulfillment_region (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_DF8DFCBB4584665A ON product_inventory (product_id)');
        $this->addSql('CREATE INDEX IDX_DF8DFCBB48027C30 ON product_inventory (fulfillment_region_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_inventory_product_location ON product_inventory (product_id, fulfillment_region_id)');
        $this->addSql('CREATE TABLE product_pricing (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, price NUMERIC(12, 2) NOT NULL, rule_type VARCHAR(20) DEFAULT NULL, rule_value NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) NOT NULL, created_at DATETIME NOT NULL, product_id INTEGER NOT NULL, price_list_id INTEGER NOT NULL, CONSTRAINT FK_3428B7834584665A FOREIGN KEY (product_id) REFERENCES product_core (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3428B7835688DED7 FOREIGN KEY (price_list_id) REFERENCES price_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_3428B7834584665A ON product_pricing (product_id)');
        $this->addSql('CREATE INDEX IDX_3428B7835688DED7 ON product_pricing (price_list_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_pricing_product_list ON product_pricing (product_id, price_list_id)');
        $this->addSql('CREATE TABLE sales_order (po_number VARCHAR(80) DEFAULT NULL, user_name VARCHAR(120) DEFAULT NULL, subtotal NUMERIC(12, 2) NOT NULL, tax NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, source VARCHAR(32) NOT NULL, special_instructions VARCHAR(255) DEFAULT NULL, fee_lines CLOB DEFAULT NULL, coupon_codes CLOB DEFAULT NULL, tax_lines CLOB DEFAULT NULL, company_snapshot CLOB DEFAULT NULL, shipping_method VARCHAR(120) DEFAULT NULL, fulfillment_region VARCHAR(160) DEFAULT NULL, created_at DATETIME NOT NULL, id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, order_number VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, invoice_date DATE DEFAULT NULL, payment_status VARCHAR(40) DEFAULT NULL, payment_method VARCHAR(120) DEFAULT NULL, payment_term VARCHAR(120) DEFAULT NULL, po_date DATE NOT NULL, company_id INTEGER NOT NULL, CONSTRAINT FK_36D222E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_36D222E551F0F81 ON sales_order (order_number)');
        $this->addSql('CREATE INDEX IDX_36D222E979B1AD6 ON sales_order (company_id)');
        $this->addSql('CREATE TABLE sales_order_address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type VARCHAR(16) NOT NULL, first_name VARCHAR(120) DEFAULT NULL, last_name VARCHAR(120) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, email_primary VARCHAR(255) DEFAULT NULL, email_secondary VARCHAR(255) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, fax VARCHAR(40) DEFAULT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, province VARCHAR(6) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, delivery_instructions CLOB DEFAULT NULL, source_address_id INTEGER DEFAULT NULL, order_id INTEGER NOT NULL, CONSTRAINT FK_3E12B0798903DE51 FOREIGN KEY (source_address_id) REFERENCES company_address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3E12B0798D9F6D38 FOREIGN KEY (order_id) REFERENCES sales_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_3E12B0798903DE51 ON sales_order_address (source_address_id)');
        $this->addSql('CREATE INDEX IDX_3E12B0798D9F6D38 ON sales_order_address (order_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_sales_order_address_type ON sales_order_address (order_id, type)');
        $this->addSql('CREATE TABLE sales_order_line (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(120) DEFAULT NULL, sku VARCHAR(80) DEFAULT NULL, quantity NUMERIC(12, 2) NOT NULL, weight VARCHAR(80) DEFAULT NULL, unit VARCHAR(80) DEFAULT NULL, tax_code VARCHAR(80) DEFAULT NULL, cost NUMERIC(12, 2) NOT NULL, price NUMERIC(12, 2) NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, batch VARCHAR(120) DEFAULT NULL, sort_order INTEGER DEFAULT 0 NOT NULL, order_id INTEGER NOT NULL, product_id INTEGER DEFAULT NULL, CONSTRAINT FK_93D9398D8D9F6D38 FOREIGN KEY (order_id) REFERENCES sales_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_93D9398D4584665A FOREIGN KEY (product_id) REFERENCES product_core (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_93D9398D8D9F6D38 ON sales_order_line (order_id)');
        $this->addSql('CREATE INDEX IDX_93D9398D4584665A ON sales_order_line (product_id)');
        $this->addSql('CREATE TABLE sales_order_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_name VARCHAR(255) DEFAULT NULL, comment CLOB NOT NULL, type VARCHAR(64) NOT NULL, customer_notified BOOLEAN NOT NULL, created_at DATETIME NOT NULL, order_id INTEGER NOT NULL, CONSTRAINT FK_F02A7FEC8D9F6D38 FOREIGN KEY (order_id) REFERENCES sales_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_F02A7FEC8D9F6D38 ON sales_order_log (order_id)');
        $this->addSql('CREATE TABLE sales_order_payment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, received_at DATE NOT NULL, method VARCHAR(64) NOT NULL, amount NUMERIC(12, 2) NOT NULL, comment VARCHAR(255) DEFAULT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, order_id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, CONSTRAINT FK_5E745BF58D9F6D38 FOREIGN KEY (order_id) REFERENCES sales_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_5E745BF5A76ED395 FOREIGN KEY (user_id) REFERENCES admin_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E745BF5FC72F97E ON sales_order_payment (stripe_payment_intent_id)');
        $this->addSql('CREATE INDEX IDX_5E745BF58D9F6D38 ON sales_order_payment (order_id)');
        $this->addSql('CREATE INDEX IDX_5E745BF5A76ED395 ON sales_order_payment (user_id)');
        $this->addSql('CREATE TABLE sales_tax (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, province_name VARCHAR(120) NOT NULL, abbreviation VARCHAR(16) NOT NULL, tax_type VARCHAR(40) NOT NULL, rate NUMERIC(8, 3) DEFAULT 0 NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, slug VARCHAR(100) DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B95156C989D9B62 ON sales_tax (slug)');
        $this->addSql('CREATE TABLE url_redirect (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, source_path VARCHAR(500) NOT NULL, destination_type VARCHAR(20) NOT NULL, destination_url VARCHAR(2048) DEFAULT NULL, redirect_type SMALLINT NOT NULL, query_handling VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, destination_category_id INTEGER DEFAULT NULL, CONSTRAINT FK_A16CF0A2377476D9 FOREIGN KEY (destination_category_id) REFERENCES product_category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_A16CF0A2377476D9 ON url_redirect (destination_category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_URL_REDIRECT_SOURCE_PATH ON url_redirect (source_path)');
        $this->addSql('CREATE TABLE rememberme_token (series VARCHAR(88) NOT NULL, value VARCHAR(88) NOT NULL, lastUsed DATETIME NOT NULL, class VARCHAR(100) DEFAULT \'\' NOT NULL, username VARCHAR(200) NOT NULL, PRIMARY KEY (series))');

        // These four have no Doctrine entity (read/written via raw DBAL in Admin\ConfigController's
        // CONFIG_TABLES registry and AbstractAdminController's payment-term dropdown, plus the
        // RateLimiterGate-adjacent throttle store for the db-admin.php gateway that runs outside the
        // kernel) so doctrine:migrations:diff never sees them. See RawSqlTablesSurviveTheChainTest.
        $this->addSql('CREATE TABLE payment_term (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(180) NOT NULL, description CLOB DEFAULT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, sort_order INTEGER DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE credit_memo_type (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE shipping_zone (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, area_name VARCHAR(180) NOT NULL, delivery_days VARCHAR(80) DEFAULT NULL, free_shipping_minimum NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, delivery_fee NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, status VARCHAR(32) DEFAULT \'Active\' NOT NULL, sort_order INTEGER DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE db_console_throttle (ip_address VARCHAR(45) PRIMARY KEY NOT NULL, window_start INTEGER NOT NULL, attempts INTEGER NOT NULL)');

        // geo_country / geo_province -- single-sourced from RegionSeedData rather than duplicated
        // here as literal rows, so this and RegionSeeder/Region can never disagree about the list.
        // A subselect on geo_country.code resolves country_id: addSql() queues SQL for execution
        // after up() returns, so lastInsertId() immediately after an addSql() call would run before
        // that INSERT ever actually executed.
        $countrySortOrder = 0;
        foreach (RegionSeedData::COUNTRIES as $countryCode => $countryName) {
            $this->addSql(
                'INSERT INTO geo_country (code, name, status, sort_order) VALUES (:code, :name, :status, :sort_order)',
                ['code' => $countryCode, 'name' => $countryName, 'status' => 'Active', 'sort_order' => $countrySortOrder],
            );

            $provinceSortOrder = 0;
            foreach (RegionSeedData::PROVINCES[$countryCode] as $provinceCode => $provinceName) {
                $this->addSql(
                    'INSERT INTO geo_province (country_id, code, name, status, sort_order)
                     SELECT c.id, :code, :name, :status, :sort_order FROM geo_country c WHERE c.code = :country',
                    ['country' => $countryCode, 'code' => $provinceCode, 'name' => $provinceName, 'status' => 'Active', 'sort_order' => $provinceSortOrder],
                );
                ++$provinceSortOrder;
            }

            ++$countrySortOrder;
        }

        // email_template -- 22 rows
        foreach ([
            ['company_registration', 'Company Registration', 'Customer', 'Company registration received - {{ site_name() }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Company Registration{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Company registration received</h2>

    <p>Hello{% if contact_name is defined and contact_name %} <strong>{{ contact_name }}</strong>{% endif %},</p>

    <p>
        Thanks for registering <strong>{{ company_name|default(\'your company\') }}</strong> with {{ site_name() }}.
        We\'ve received your company details successfully.
    </p>

    <div class="order-summary">
        <p style="margin: 0 0 12px 0; font-weight: 800; color: #0f172a;">Registration summary</p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Company</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; font-weight: 700; text-align: right;">{{ company_name|default(\'-\') }}</td>
            </tr>
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Company Code</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; text-align: right;">{{ company_code|default(\'-\') }}</td>
            </tr>
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Company Email</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; text-align: right;">{{ company_email|default(\'-\') }}</td>
            </tr>
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Login Email</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; text-align: right;">{{ user_email|default(\'-\') }}</td>
            </tr>
        </table>
    </div>

    <p>Your registration is pending approval. We will email you again as soon as an administrator activates your account.</p>

    <p style="margin-top: 30px; font-size: 13px; color: #64748b;">
        If you didn\'t request this registration, please ignore this email{% if support_email is defined and support_email %} or contact support at <span class="highlight">{{ support_email }}</span>{% endif %}.
    </p>
{% endblock %}', 'Sent to the company email after a successful registration.', 'Active'],
            ['company_registration_admin_alert', 'Company Registration Admin Alert', 'Admin', 'New company registration pending approval', '{% extends \'emails/layout.html.twig\' %}

{% block title %}New Company Registration{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">New company registration pending approval</h2>

    <p>A new company registration has been submitted and is waiting for admin review.</p>

    <div class="order-summary">
        <p style="margin: 0 0 12px 0; font-weight: 800; color: #0f172a;">Registration summary</p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Company</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; font-weight: 700; text-align: right;">{{ company_name|default(\'-\') }}</td>
            </tr>
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Company Code</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; text-align: right;">{{ company_code|default(\'-\') }}</td>
            </tr>
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Company Email</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; text-align: right;">{{ company_email|default(\'-\') }}</td>
            </tr>
            <tr>
                <td style="padding: 6px 0; font-size: 14px; color: #475569;">Login Email</td>
                <td style="padding: 6px 0; font-size: 14px; color: #0f172a; text-align: right;">{{ user_email|default(\'-\') }}</td>
            </tr>
        </table>
    </div>

    <p>Please review the registration and activate the customer user when approved.</p>

    <div style="text-align: center; margin-top: 30px;">
        <a href="{{ admin_url|default(\'#\') }}" class="button">Review Customer Users</a>
    </div>
{% endblock %}', 'Sent to admins when a new company registration requires approval.', 'Active'],
            ['email_changed', 'Email Change Notification', 'Customer', 'Your account\'s email has changed - {{ site_name() }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Your Account\'s Email Has Changed{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Your account\'s email has changed</h2>
    <p>Hello,</p>
    <p>This is a confirmation that the email address on your {{ site_name() }} account was recently changed by an administrator.</p>

    <div class="order-summary">
        <div class="summary-row">
            <span>Previous email</span>
            <span>{{ old_email|default(\'-\') }}</span>
        </div>
        <div class="summary-row">
            <span>New email</span>
            <span>{{ new_email|default(\'-\') }}</span>
        </div>
    </div>

    <p style="margin-top: 30px; font-size: 14px; color: #64748b;">
        {% if support_email is defined and support_email %}
            If you did not expect this change, please <a href="mailto:{{ support_email }}">contact us</a> immediately at {{ support_email }}.
        {% else %}
            If you did not expect this change, please contact us immediately.
        {% endif %}
    </p>
{% endblock %}', 'Sent to a customer\'s previous email address when an admin changes their account email.', 'Active'],
            ['forgot_password', 'forgot_password', 'Customer', 'Reset your password', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Password Reset Request{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Password Reset</h2>
    <p>Hello <strong>{{ user_email|default(\'User\') }}</strong>,</p>
    <p>We received a request to reset your password for {{ site_name() }}. If you didn\'t make this request, you can safely ignore this email.</p>

    <div style="text-align: center; margin-top: 25px;">
        <a href="{{ reset_url|default(\'#\') }}" class="button" style="border-radius: 999px;">Reset My Password</a>
    </div>

    <p style="margin-top: 30px; font-size: 13px; color: #64748b;">
        For security, this link will expire in 1 hour.
    </p>
{% endblock %}', null, 'Active'],
            ['invite', 'Invite (Legacy)', 'Customer', 'Invitation to {{ site_name() }}', '{% extends \'emails/layout.html.twig\' %}
{% block body %}
<h2 style="margin-top: 0; color: #0f172a;">Welcome!</h2>
<p>Hello <strong>{{ user_email|default(\'User\') }}</strong>,</p>
<p>You have been invited to join the {{ site_name() }} portal. To get started and set up your password, please click the button below:</p>
<div style="text-align: center; margin-top: 25px;"><a href="{{ reset_url|default(\'#\') }}" class="button" style="border-radius: 999px;">Set Up My Account</a></div>
<p style="margin-top: 30px; font-size: 13px; color: #64748b;">This invitation will expire in 1 hour. If you didn\'t request this, you can ignore this email.</p>
{% endblock %}', 'Legacy alias for invitation template.', 'Active'],
            ['invoice_customer', 'Invoice (Customer)', 'Customer', 'Invoice for Order #{{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Invoice for Order #{{ order.orderNumber }}{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Order Confirmation</h2>
    <p>Hello <strong>{{ order.company.name }}</strong>,</p>
    <p>Thank you for your order! We have processed your invoice for order <span class="highlight">#{{ order.orderNumber }}</span>. Please find the PDF invoice attached to this email for your records.</p>

    <div class="order-summary">
        <div class="summary-row">
            <span>Order Number:</span>
            <strong>{{ order.orderNumber }}</strong>
        </div>
        <div class="summary-row">
            <span>Order Date:</span>
            <strong>{{ order.poDate|date(\'F j, Y\') }}</strong>
        </div>
        <div class="summary-row">
            <span>Grand Total:</span>
            <strong>${{ order.total|default(0)|number_format(2) }}</strong>
        </div>
    </div>

    <p>If you have any questions regarding this invoice or your order status, please don\'t hesitate to reach out to our billing department.</p>

    <div style="text-align: center;">
        <a href="{{ order_url|default(\'#\') }}" class="button">View Order Details</a>
    </div>
{% endblock %}', 'Email body used when sending invoice to customer/company.', 'Active'],
            ['invoice_self', 'Invoice (Internal)', 'Admin', 'Internal: Invoice for Order #{{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Internal: Invoice for Order #{{ order.orderNumber }}{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Internal Invoice Copy</h2>
    <p>This is an internal copy of the invoice generated for order <span class="highlight">#{{ order.orderNumber }}</span>.</p>

    <div class="order-summary">
        <div class="summary-row">
            <span>Company:</span>
            <strong>{{ order.company.name }}</strong>
        </div>
        <div class="summary-row">
            <span>Order #:</span>
            <strong>{{ order.orderNumber }}</strong>
        </div>
        <div class="summary-row">
            <span>Total Amount:</span>
            <strong>${{ order.total|default(0)|number_format(2) }}</strong>
        </div>
    </div>

    <p>The PDF attachment is identical to the version sent to the customer.</p>

    <div style="text-align: center;">
        <a href="{{ admin_url|default(\'#\') }}" class="button">Review Order</a>
    </div>
{% endblock %}', 'Email body used when sending internal invoice copy.', 'Active'],
            ['login', 'login', 'Customer', 'Login notification', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Login Notification{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">New Login Detected</h2>
    <p>Hello <strong>{{ user_email|default(\'User\') }}</strong>,</p>
    <p>This is a courtesy notification that a new login was recorded for your {{ site_name() }} account.</p>

    <div class="order-summary">
        <div class="summary-row">
            <span>Date &amp; Time:</span>
            <strong>{{ "now"|date(\'F j, Y g:i A\') }}</strong>
        </div>
        <div class="summary-row">
            <span>Account:</span>
            <strong>{{ user_email|default(\'-\') }}</strong>
        </div>
    </div>

    <p>If this was you, you can safely ignore this email. If you did not log in, we recommend resetting your password immediately.</p>

    <div style="text-align: center;">
        <a href="{{ security_url|default(\'#\') }}" class="button">Security Settings</a>
    </div>
{% endblock %}', null, 'Active'],
            ['new_shipping_address', 'New shipping address', 'Customer', 'Shipping address updated', '{% extends \'emails/layout.html.twig\' %}
{% block body %}
<h2 style="margin-top: 0; color: #0f172a;">Shipping address updated</h2>
<p>Your shipping address has been updated successfully.</p>
{% endblock %}', 'Shipping address update notification (optional).', 'Active'],
            ['new_user_invited', 'New User Invited', 'Customer', 'Invitation to {{ site_name() }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Welcome to {{ site_name() }}{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Welcome!</h2>
    <p>Hello <strong>{{ user_email|default(\'User\') }}</strong>,</p>
    <p>You have been invited to join the {{ site_name() }} portal. To get started and set up your password, please click the button below:</p>

    <div style="text-align: center; margin-top: 25px;">
        <a href="{{ reset_url|default(\'#\') }}" class="button" style="border-radius: 999px;">Set Up My Account</a>
    </div>

    <p style="margin-top: 30px; font-size: 13px; color: #64748b;">
        This invitation will expire in 1 hour. If you didn\'t request this, you can ignore this email.
    </p>
{% endblock %}', 'Sent when an admin invites a new user to set a password.', 'Active'],
            ['order_approved', 'Order Approved', 'Customer', 'Order approved: {{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}
{% block body %}
<h2 style="margin-top: 0; color: #0f172a;">Order approved</h2>
<p>Hello <strong>{{ order.company.name|default(\'Customer\') }}</strong>,</p>
<p>Your order <span class="highlight">#{{ order.orderNumber|default(\'\') }}</span> has been approved.</p>
{% endblock %}', 'Order approved notification (optional).', 'Active'],
            ['order_cancelled', 'Order Cancelled', 'Customer', 'Order cancelled: {{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}
{% block body %}
<h2 style="margin-top: 0; color: #0f172a;">Order cancelled</h2>
<p>Hello <strong>{{ order.company.name|default(\'Customer\') }}</strong>,</p>
<p>Your order <span class="highlight">#{{ order.orderNumber|default(\'\') }}</span> was cancelled. If you have questions, please contact support.</p>
{% endblock %}', 'Order cancelled notification (optional).', 'Active'],
            ['order_message', 'Order Note For Customer', 'Customer', 'Message about order {{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}New Message Regarding Order #{{ order.orderNumber }}{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">New Message</h2>
    <p>Hello <strong>{{ order.company.name }}</strong>,</p>
    <p>There is a new message regarding your order <span class="highlight">#{{ order.orderNumber }}</span>:</p>

    <div class="order-summary" style="font-style: italic; border-left: 4px solid #0f766e;">
        {{ message|default(\'\')|nl2br }}
    </div>

    <p>If you have any questions, feel free to reply to this email or view your order details online.</p>

    <div style="text-align: center;">
        <a href="{{ order_url|default(\'#\') }}" class="button">View My Order</a>
    </div>

    <div class="order-summary" style="background: transparent; border: none; border-top: 1px solid #e2e8f0; margin-top: 30px; padding: 20px 0 0 0;">
        <p style="margin: 0; font-size: 14px;"><strong>Order Number:</strong> {{ order.orderNumber }}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px;"><strong>Date:</strong> {{ "now"|date(\'F j, Y\') }}</p>
    </div>
{% endblock %}', 'Sent to the company when an admin posts an order note/message.', 'Active'],
            ['order_received', 'Order Received', 'Customer', 'Order received: {{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}
{% block body %}
<h2 style="margin-top: 0; color: #0f172a;">Order received</h2>
<p>Hello <strong>{{ order.company.name|default(\'Customer\') }}</strong>,</p>
<p>We\'ve received your order <span class="highlight">#{{ order.orderNumber|default(\'\') }}</span>. We\'ll notify you as it moves forward.</p>
{% endblock %}', 'Order received confirmation (optional).', 'Active'],
            ['order_received_admin', 'Order Received (Admin)', 'Admin', 'New order received: {{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}New Order Received{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">New order received</h2>
    <p>A new order <span class="highlight">#{{ order.orderNumber }}</span> was placed by <strong>{{ company.name|default(\'a customer\') }}</strong>.</p>

    <div class="order-summary">
        <div class="summary-row">
            <span>Order Total:</span>
            <strong>${{ order.total|default(0)|number_format(2) }}</strong>
        </div>
    </div>

    <div style="text-align: center;">
        <a href="{{ admin_url|default(\'#\') }}" class="button">Review Order</a>
    </div>
{% endblock %}', 'Sent to active admins when a new order is placed (checkout or quote approval).', 'Active'],
            ['order_status_update', 'Order Status Update', 'Customer', 'Order Update: {{ order.orderNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Order Status Updated #{{ order.orderNumber }}{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Order Update</h2>
    <p>Hello <strong>{{ order.company.name }}</strong>,</p>
    <p>The status of your order <span class="highlight">#{{ order.orderNumber }}</span> has been updated.</p>

    <div style="text-align: center; margin: 30px 0;">
        <span style="display: inline-block; padding: 12px 30px; background: #f0fdfa; color: #0f766e; border-radius: 9999px; font-weight: 800; font-size: 18px; border: 2px solid #ccfbf1;">
            {{ status|default(\'Updated\') }}
        </span>
    </div>

    <p>You can view your order details and track its progress online.</p>

    <div style="text-align: center;">
        <a href="{{ order_url|default(\'#\') }}" class="button">View My Order</a>
    </div>

    <div class="order-summary" style="background: transparent; border: none; border-top: 1px solid #e2e8f0; margin-top: 30px; padding: 20px 0 0 0;">
        <p style="margin: 0; font-size: 14px;"><strong>Order Number:</strong> {{ order.orderNumber }}</p>
        <p style="margin: 5px 0 0 0; font-size: 14px;"><strong>Updated At:</strong> {{ "now"|date(\'F j, Y g:i A\') }}</p>
    </div>
{% endblock %}', 'Sent to the company when an order status changes.', 'Active'],
            ['quote_approved_admin', 'Quote Approved (Admin)', 'Admin', 'Quote approved: {{ estimate.documentNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Quote Approved{% endblock %}

{% block body %}
    <p>Hi,</p>
    <h2 style="margin-top: 0; color: #0f172a;">Quote Request ({{ estimate.documentNumber }}) has been accepted by the customer.</h2>
    <p>It has been converted to order <span class="highlight">#{{ order.orderNumber }}</span>.</p>

    {% include \'emails/_quote_summary.html.twig\' %}

    <div style="text-align: center; margin-top: 10px;">
        <a href="{{ admin_url|default(\'#\') }}" class="button">Review Quote</a>
    </div>
{% endblock %}', 'Sent to active admins when a customer approves a priced quote.', 'Active'],
            ['quote_declined_admin', 'Quote Declined (Admin)', 'Admin', 'Quote declined: {{ estimate.documentNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Quote Declined{% endblock %}

{% block body %}
    <p>Hi,</p>
    <h2 style="margin-top: 0; color: #0f172a;">Quote Request ({{ estimate.documentNumber }}) has been declined by the customer.</h2>

    {% include \'emails/_quote_summary.html.twig\' %}

    <div style="text-align: center; margin-top: 10px;">
        <a href="{{ admin_url|default(\'#\') }}" class="button">Review Quote</a>
    </div>
{% endblock %}', 'Sent to active admins when a customer declines/cancels a quote.', 'Active'],
            ['quote_provided', 'Quote Provided', 'Customer', 'Your quote is ready: {{ estimate.documentNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Your Quote Is Ready{% endblock %}

{% block body %}
    <p>Hey {{ estimate.company.name|default(\'there\') }},</p>
    <h2 style="margin-top: 0; color: #0f172a;">Your quote is ready for your review &amp; approval</h2>
    <p><a href="{{ estimate_url|default(\'#\') }}" class="highlight" style="text-decoration: none;">View quote details</a></p>

    {% include \'emails/_quote_summary.html.twig\' %}

    <div style="text-align: center; margin-top: 20px;">
        <a href="{{ estimate_url|default(\'#\') }}" class="button" style="background: #16a34a;">APPROVE</a>
    </div>
    <p style="text-align: center; font-size: 13px; color: #64748b; margin-top: 12px;">Please approve the quote to proceed with your order.</p>
{% endblock %}', 'Sent to the customer when admin finishes pricing a quote and sends it for approval.', 'Active'],
            ['quote_request_admin', 'Quote Request (Admin)', 'Admin', 'New quote request: {{ estimate.documentNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}New Quote Request{% endblock %}

{% block body %}
    <p>Hi,</p>
    <h2 style="margin-top: 0; color: #0f172a;">Quote request received. Please review and provide a quote to the customer as soon as possible.</h2>

    {% include \'emails/_quote_summary.html.twig\' %}

    <div style="text-align: center; margin-top: 10px;">
        <a href="{{ admin_url|default(\'#\') }}" class="button">Review Quote Request</a>
    </div>
{% endblock %}', 'Sent to active admins when a customer submits a quote request.', 'Active'],
            ['quote_request_received', 'Quote Request Received', 'Customer', 'Quote request received: {{ estimate.documentNumber|default(\'\') }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Quote Request Received{% endblock %}

{% block body %}
    <p>Hi,</p>
    <h2 style="margin-top: 0; color: #0f172a;">Quote request received</h2>
    <p>We\'ve received your quote request. Our team will review it and send you pricing as soon as possible.</p>

    {% include \'emails/_quote_summary.html.twig\' %}

    <div style="text-align: center; margin-top: 10px;">
        <a href="{{ estimate_url|default(\'#\') }}" class="button">View My Quote Request</a>
    </div>
{% endblock %}', 'Sent to the customer when a quote request (estimate) is submitted.', 'Active'],
            ['register', 'register', 'Customer', 'Your account is now active - {{ site_name() }}', '{% extends \'emails/layout.html.twig\' %}

{% block title %}Your Account Is Active{% endblock %}

{% block body %}
    <h2 style="margin-top: 0; color: #0f172a;">Your account is now active</h2>
    <p>Hello <strong>{{ user_email|default(\'User\') }}</strong>,</p>
    <p>Your company registration has been approved and your account is now active.</p>

    <p>You can now log in to view the catalog, manage your company details, and place orders.</p>

    <div style="text-align: center; margin-top: 30px;">
        <a href="{{ login_url|default(\'#\') }}" class="button">Log In to Your Account</a>
    </div>
{% endblock %}', null, 'Active'],
        ] as [$code, $module, $sent_to, $subject, $body, $description, $status]) {
            $this->addSql('INSERT INTO email_template (code, module, sent_to, subject, body, description, status, created_at, updated_at) VALUES (:code, :module, :sent_to, :subject, :body, :description, :status, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)', ['code' => $code, 'module' => $module, 'sent_to' => $sent_to, 'subject' => $subject, 'body' => $body, 'description' => $description, 'status' => $status]);
        }

        // app_setting -- 22 rows
        foreach ([
            ['app_email', 'App Email', null, 'Primary contact email address for the business/application.', null],
            ['app_name', 'App Name', null, 'Shown in the site header, invoices, and email templates.', null],
            ['base_currency', 'Base Currency', null, 'Used for product pricing defaults, price-list display, and order totals.', null],
            ['billing_email', 'Billing Email', null, 'Accounts receivable / billing contact email address.', null],
            ['company_address', 'Company Address', null, 'Street address for invoices and contact details.', null],
            ['company_city', 'Company City', null, 'City for invoices and contact details.', null],
            ['company_country', 'Company Country', null, 'Country for invoices and contact details.', null],
            ['company_name', 'Company Name', null, 'Legal or trading name shown on invoices and emails (if used).', null],
            ['company_phone', 'Company Phone', null, 'Primary phone number for the business.', null],
            ['company_postal_code', 'Company Postal Code', null, 'Postal/ZIP code for invoices and contact details.', null],
            ['company_state', 'Company State/Province', null, 'State or province for invoices and contact details.', null],
            ['fulfillment_regions', 'Fulfillment Regions', 'Main
Overflow
Supplier Direct', 'Newline-separated list of fulfillment regions. The first region is the default and can\'t be deleted.', null],
            ['invoice_footer_note', 'Invoice Footer Note', null, 'Optional note printed in the invoice footer (if used).', null],
            ['invoice_payment_note', 'Invoice Payment Note', null, 'Shown on invoices to explain how customers should pay.', null],
            ['logo_url', 'Logo URL', null, 'Absolute or relative URL to a logo image used in UI/emails (if used).', null],
            ['privacy_url', 'Privacy URL', null, 'Link to Privacy Policy page (if used).', null],
            ['returns_url', 'Returns URL', null, 'Link to Returns/Refund policy page (if used).', null],
            ['sales_email', 'Sales Email', null, 'Sales contact email address.', null],
            ['support_email', 'Support Email', null, 'Customer support email address (used for contact links and support messaging).', null],
            ['terms_url', 'Terms URL', null, 'Link to Terms & Conditions page (if used).', null],
            ['timezone', 'Timezone', null, 'IANA timezone identifier, e.g. America/New_York or Asia/Kolkata (if used).', null],
            ['website_url', 'Website URL', null, 'Public website URL used in emails/footers (if used).', null],
        ] as [$setting_key, $name, $setting_value, $description, $category]) {
            $this->addSql('INSERT INTO app_setting (setting_key, name, setting_value, description, category, created_at, updated_at) VALUES (:setting_key, :name, :setting_value, :description, :category, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)', ['setting_key' => $setting_key, 'name' => $name, 'setting_value' => $setting_value, 'description' => $description, 'category' => $category]);
        }

    }

    public function down(Schema $schema): void
    {
        // Deliberately not implemented: this migration IS the baseline. A fresh install
        // that needs to undo it should drop the database, not migrate down.
    }
}
