<?php

declare(strict_types=1);

namespace App\Tests\Service;

use App\Service\CompanyListScope;
use PHPUnit\Framework\TestCase;

/**
 * The parsing half of the invoice and quote grids' customer-id filter.
 *
 * AdminDocumentListCompanyScopeCest drives the screens and is where the filter is proved to filter.
 * This covers the same rules one level down, where every odd spelling can be enumerated cheaply —
 * and in particular the two that decide whether a bad id can be mistaken for a good one:
 *
 *   - `12abc` must NOT read as customer 12. A plain (int) cast says 12 and shows a customer nobody
 *     asked for; the grid then looks exactly like the one that was asked for.
 *   - an empty value must NOT mean "no such customer". The company picker posts `company_id=""`
 *     before anyone has chosen, and on a list that means "unscoped", not "show nothing".
 */
final class CompanyListScopeTest extends TestCase
{
    public function testAnAbsentParameterAsksForNoScope(): void
    {
        self::assertNull(CompanyListScope::requestedIdIn([], 'InvoiceSearch'));
        self::assertNull(CompanyListScope::requestedIdIn(['filters' => ['company' => 'Acme']], 'InvoiceSearch'));
    }

    public function testTheGroupedSpellingIsRead(): void
    {
        self::assertSame('42', CompanyListScope::requestedIdIn(['InvoiceSearch' => ['company_id' => '42']], 'InvoiceSearch'));
    }

    public function testTheBareSpellingIsRead(): void
    {
        self::assertSame('42', CompanyListScope::requestedIdIn(['company_id' => '42'], 'InvoiceSearch'));
    }

    /** Each grid reads its own group, so one screen's link cannot scope another's list. */
    public function testAnotherGridsGroupIsNotRead(): void
    {
        self::assertNull(CompanyListScope::requestedIdIn(['OrderSearch' => ['company_id' => '42']], 'InvoiceSearch'));
    }

    public function testAnEmptyValueAsksForNoScope(): void
    {
        self::assertNull(CompanyListScope::requestedIdIn(['company_id' => ''], 'InvoiceSearch'));
        self::assertNull(CompanyListScope::requestedIdIn(['company_id' => '   '], 'InvoiceSearch'));
        self::assertNull(CompanyListScope::requestedIdIn(['InvoiceSearch' => ['company_id' => '']], 'InvoiceSearch'));
    }

    /** Named, but not with a value: it still asks for a scope, so it must still fail closed. */
    public function testANonScalarValueStillCountsAsAsking(): void
    {
        self::assertSame('', CompanyListScope::requestedIdIn(['company_id' => ['42']], 'InvoiceSearch'));
    }

    /**
     * A screen may spell the un-nested parameter its own way, and the sales return grid does.
     *
     * `/admin/sales-return/index?company=` predates the nested shape and is still generated by that
     * screen's own links, so it is passed in rather than deleted — dropping the spelling would have
     * UNSCOPED every link using it, which is the failure this class exists to prevent. It is read
     * through here so it gets the same refusal to cast: `?company=12abc` is unresolved, never
     * customer 12.
     */
    public function testTheBareParameterNameIsConfigurable(): void
    {
        $keys = ['company', 'company_id'];

        self::assertSame('42', CompanyListScope::requestedIdIn(['company' => '42'], 'SalesReturnSearch', $keys));
        self::assertSame('12abc', CompanyListScope::requestedIdIn(['company' => '12abc'], 'SalesReturnSearch', $keys));
        self::assertFalse(CompanyListScope::isIdShaped('12abc'));

        // Both spellings are accepted, and the default list does not answer this screen's own.
        self::assertSame('42', CompanyListScope::requestedIdIn(['company_id' => '42'], 'SalesReturnSearch', $keys));
        self::assertNull(CompanyListScope::requestedIdIn(['company' => '42'], 'SalesReturnSearch'));

        // Precedence: nested first, then the bare keys in the order given.
        self::assertSame(
            '7',
            CompanyListScope::requestedIdIn(
                ['SalesReturnSearch' => ['company_id' => '7'], 'company' => '8', 'company_id' => '9'],
                'SalesReturnSearch',
                $keys,
            ),
        );
        self::assertSame('8', CompanyListScope::requestedIdIn(['company' => '8', 'company_id' => '9'], 'SalesReturnSearch', $keys));

        // An empty value is somebody having cleared the box, not a reason to try the next spelling.
        self::assertNull(CompanyListScope::requestedIdIn(['company' => '', 'company_id' => '9'], 'SalesReturnSearch', $keys));
    }

    public function testOnlyDigitsAboveZeroAreIdShaped(): void
    {
        self::assertTrue(CompanyListScope::isIdShaped('42'));
        self::assertTrue(CompanyListScope::isIdShaped('1'));

        // The one that a cast gets wrong, and the reason this is a regex and not an (int).
        self::assertFalse(CompanyListScope::isIdShaped('12abc'));
        self::assertFalse(CompanyListScope::isIdShaped('abc'));
        self::assertFalse(CompanyListScope::isIdShaped('-1'));
        self::assertFalse(CompanyListScope::isIdShaped('0'));
        self::assertFalse(CompanyListScope::isIdShaped('1.5'));
        self::assertFalse(CompanyListScope::isIdShaped(''));
    }

    public function testTheThreeStatesAreDistinguishable(): void
    {
        $none = CompanyListScope::none();
        self::assertFalse($none->isRequested());
        self::assertFalse($none->isUnresolved());
        self::assertNull($none->company());

        $unresolved = CompanyListScope::unresolved('99999');
        self::assertTrue($unresolved->isRequested());
        self::assertTrue($unresolved->isUnresolved());
        self::assertNull($unresolved->company());
        self::assertSame('99999', $unresolved->requestedId());
    }
}
