services:
    _defaults:
        autowire: true
        autoconfigure: true

    PaymentManualBundle\:
        resource: '../src/'

    PaymentManualBundle\Payment\ManualPaymentMethodProvider:
        tags: ['app.payment_method_provider']

    PaymentManualBundle\Menu\ManualPaymentMenuItem:
        tags: ['app.payment_menu_item']

    PaymentManualBundle\Bundle\PaymentManualBundleDescriptor:
        tags: ['app.bundle_descriptor']
