services:
    _defaults:
        autowire: true
        autoconfigure: true

    TechnicalDocsBundle\:
        resource: '../src/'

    TechnicalDocsBundle\Bundle\TechnicalDocsBundleDescriptor:
        tags: ['app.bundle_descriptor']
